services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nc}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nc}
    volumes:
      - db:/var/lib/mysql

  nextcloud:
    image: nextcloud:32-apache
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nc}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nc}
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-admin}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS:-localhost}
    volumes:
      - nextcloud:/var/www/html
      - ./:/var/www/html/custom_apps/familybudget

  cron:
    image: nextcloud:32-apache
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./:/var/www/html/custom_apps/familybudget
    entrypoint: /cron.sh

volumes:
  db:
  nextcloud:
